---
- id: ossindex:pypi:oauth2:357538
  title: "[CVE-2013-4346]  Cryptographic Issues"
  description: The Server.verify_request function in SimpleGeo python-oauth2 does
    not check the nonce, which allows remote attackers to perform replay attacks via
    a signed URL.
  affected_package: oauth2
  vulnerable_versions:
  - "<=1.5.211"
  package_manager: pypi
  cve:
  - CVE-2013-4346
  disclosed_date: 2014-05-20
  created_date: 2014-05-20
  last_modified_date: 2017-01-15
  credit:
  - OSSIndex
  references:
  - http://www.openwall.com/lists/oss-security/2013/09/12/7
  - http://www.securityfocus.com/bid/62386
  - https://github.com/simplegeo/python-oauth2/issues/129
  source_url: https://ossindex.net/resource/package/8401129290/vulnerabilities
- id: ossindex:pypi:oauth2:357539
  title: "[CVE-2013-4347]  Cryptographic Issues"
  description: The (1) make_nonce, (2) generate_nonce, and (3) generate_verifier functions
    in SimpleGeo python-oauth2 uses weak random numbers to generate nonces, which
    makes it easier for remote attackers to guess the nonce via a brute force attack.
  affected_package: oauth2
  vulnerable_versions:
  - "<=1.5.211"
  package_manager: pypi
  cve:
  - CVE-2013-4347
  disclosed_date: 2014-05-20
  created_date: 2014-05-20
  last_modified_date: 2017-01-15
  credit:
  - OSSIndex
  references:
  - http://www.openwall.com/lists/oss-security/2013/09/12/7
  - http://www.securityfocus.com/bid/62388
  - https://github.com/simplegeo/python-oauth2/issues/9
  - https://github.com/simplegeo/python-oauth2/pull/146
  source_url: https://ossindex.net/resource/package/8401129290/vulnerabilities
- id: snykio:pypi:oauth2:40013
  title: Replay Attack
  description: |
    [`oauth2`][1] is a library for OAuth version 1.9 The
    Server.verify\_request function in SimpleGeo python-oauth2 does not
    check the nonce, which allows remote attackers to perform replay attacks
    via a signed URL.



    [1]: https://pypi.python.org/pypi/oauth2
  affected_package: oauth2
  vulnerable_versions:
  - "< 1.9rc1"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-4346
  cwe:
  - CWE-310
  disclosed_date: 2013-02-05
  created_date: 2013-02-05
  last_modified_date: 2013-02-05
  credit:
  - AndrÃ© Cruz
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-4346
  - https://github.com/simplegeo/python-oauth2/issues/129
  - https://nvd.nist.gov/vuln/detail/CVE-2013-4346
  source_url: https://snyk.io/vuln/SNYK-PYTHON-OAUTH2-40013
- id: snykio:pypi:oauth2:40014
  title: Insecure Randomness
  description: |
    [`oauth2`][1] is a library for OAuth version 1.9

    Affected versions of this package are vulnerable to Insecure Randomness.
    The (1) make\_nonce, (2) generate\_nonce, and (3) generate\_verifier
    functions in SimpleGeo python-oauth2 uses weak random numbers to
    generate nonces, which makes it easier for remote attackers to guess the
    nonce via a brute force attack.



    [1]: https://pypi.python.org/pypi/oauth2
  affected_package: oauth2
  vulnerable_versions:
  - "< 1.9rc1"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-4347
  cwe:
  - CWE-310
  disclosed_date: 2014-05-20
  created_date: 2017-04-13
  last_modified_date: 2017-04-13
  credit:
  - Unknown
  references:
  - http://www.openwall.com/lists/oss-security/2013/09/12/7
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-4347
  - https://github.com/simplegeo/python-oauth2/issues/9
  - https://github.com/simplegeo/python-oauth2/pull/146
  source_url: https://snyk.io/vuln/SNYK-PYTHON-OAUTH2-40014
- id: victims:pypi:oauth2:2013-4346
  title: 'oauth2: signature check ignores nonce when validating signed urls'
  affected_package: oauth2
  vulnerable_versions:
  - "<=1.5.211"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-4346
  cvss_v2_score: 4.3
  credit:
  - Victims CVE Database
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-4346
  - https://github.com/simplegeo/python-oauth2/issues/129
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2013/4346.yaml
- id: victims:pypi:oauth2:2013-4347
  title: 'oauth2: uses poor PRNG in nonce'
  affected_package: oauth2
  vulnerable_versions:
  - "<=1.5.211"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2013-4347
  cvss_v2_score: 4.3
  credit:
  - Victims CVE Database
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-4347
  - https://github.com/simplegeo/python-oauth2/issues/9
  source_url: https://github.com/victims/victims-cve-db/blob/master/database/python/2013/4347.yaml
